name: create-release-and-trigger-publish

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  trigger-publish:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Trigger NPM publish
      run: |
        'curl -X POST -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer ${process.env.GITHUB_TOKEN}" https://api.github.com/repos/verasthiago/verascli/dispatches -d '{"event_type": "publish-stable-npm","client_payload": {"ref": "${GITHUB_REF##*/}"}}'
