name: teste

on:
  repository_dispatch:
    types: [teste]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - name: Deploy on NPM
        run: |
          echo "${{ github.event.client_payload.ref }}"
          echo "${{ github.event.client_payload }}"
          echo "${{ github.event.client_payload.testando }}"
          yarn install --ignore-scripts
          yarn build
          npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            IS_CI: "true"
