name: publish-stable-npm

on:
  repository_dispatch:
    types: [publish-stable-npm]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Deploy on NPM
        run: |
          yarn install --ignore-scripts
          yarn build
          npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
            IS_CI: "true"
