name: teste

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger-publish:
    runs-on: ubuntu-latest
    needs: [create-release]
    steps:
    - name: Trigger NPM publish
      run: echo "${GITHUB_REF#refs/heads/}"
