name: teste

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy on NPM
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          echo "${github.event.pull_request.head.ref}"
          echo "${github.event}"
          echo "${github.event.commit.head.ref}"
          echo "${github.event.push.head.ref}"
          

