name: teste

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: nelonoel/branch-name@v1.0.1
      # Use branch name for whatever purpose
      - name: Deploy on NPM
        run: |
          echo "${BRANCH_MANME}"
